### ISSUE TITLE
Error in running the sat solver

### ISSUE THREAD

**Issue by ghost** [lnestor/sat_attack#1]
VirtualBox:~/sat_attack$ python3 sat_attack/run.py /home/vamsi/sat_attack/benchmarks/sample/sample_locked.v /home/vamsi/sat_attack/benchmarks/sample/sample_unlocked.v
Traceback (most recent call last):
  File "sat_attack/run.py", line 4, in <module>
    import sat_attack
  File "/home/vamsi/sat_attack/sat_attack/sat_attack.py", line 1, in <module>
    import z3
ModuleNotFoundError: No module named 'z3'

**Comment by lnestor** [comment]
Try installing z3-solver with pip by doing `pip3 install z3-solver`
